# Generated by Django 3.0.4 on 2020-03-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='categories',
            field=models.ManyToManyField(default=None, null=True, to='main.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='application',
            name='developer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Developer', verbose_name='Разработчик'),
        ),
        migrations.AlterField(
            model_name='version',
            name='published',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата релиза'),
        ),
    ]
