# Generated by Django 3.0.4 on 2020-03-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200326_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название элемента'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название паттерна'),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание изменений'),
        ),
    ]
