# Generated by Django 3.0.4 on 2020-03-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200326_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название элемента'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название паттерна'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='elements',
            field=models.ManyToManyField(blank=True, null=True, to='main.Element', verbose_name='Элементы'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='pattern',
            field=models.ManyToManyField(blank=True, null=True, to='main.Pattern', verbose_name='Паттерн'),
        ),
    ]
