# Generated by Django 3.0.4 on 2020-03-27 11:32

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200326_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen',
            field=models.ImageField(blank=True, null=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Снимок экрана'),
        ),
    ]
