# Generated by Django 3.0.4 on 2020-03-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200327_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubElement',
            fields=[
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.element',),
        ),
        migrations.CreateModel(
            name='SuperElement',
            fields=[
            ],
            options={
                'verbose_name': 'Группа элементов',
                'verbose_name_plural': 'Группы элементов',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.element',),
        ),
        migrations.AddField(
            model_name='element',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='destination',
            field=models.CharField(default='Плонета жопа', max_length=100, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название элемента'),
        ),
        migrations.AddField(
            model_name='element',
            name='super_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.SuperElement', verbose_name='Группа элементов'),
        ),
    ]
