# Generated by Django 3.0.4 on 2020-03-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200329_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='elements',
            field=models.ManyToManyField(blank=True, null=True, to='main.SubElement', verbose_name='Элементы'),
        ),
    ]
