# Generated by Django 3.0.4 on 2020-03-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200329_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPattern',
            fields=[
            ],
            options={
                'verbose_name': 'Паттерн',
                'verbose_name_plural': 'Паттерны',
                'ordering': ('super_pattern', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.pattern',),
        ),
        migrations.CreateModel(
            name='SuperPattern',
            fields=[
            ],
            options={
                'verbose_name': 'Группа паттернов',
                'verbose_name_plural': 'Группы паттернов',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.pattern',),
        ),
        migrations.AlterModelOptions(
            name='subelement',
            options={'ordering': ('super_element', 'order', 'name'), 'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AddField(
            model_name='pattern',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='super_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.SuperPattern', verbose_name='Группа паттернов'),
        ),
    ]
