# Generated by Django 3.0.4 on 2020-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200329_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='pattern',
            field=models.ManyToManyField(blank=True, null=True, to='main.SubPattern', verbose_name='Паттерн'),
        ),
    ]
